import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Image from "next/image";
import "./globals.css";

import NavBar from "@/components/NavBar";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <NavBar />
        <main>{children}</main>
        <footer>
          <div className="max-w-5xl mx-auto">
            <Image
              src="/footer.png"
              className="w-full"
              alt="EastWest footer"
              width={0}
              height={0}
              sizes="100vw"
            />
          </div>
        </footer>
      </body>
    </html>
  );
}
